<div class="slider  ">

		<div class="myslider fade" style="display: block;">
			<div class="txt">
				<h1>ADIDAS BRAND</h1>
				<p>This WEBSITE IS FOR YOU</p>
			</div>
			<div class="style1">
				<img src="../Image/product3.jpg" style="width:100% ;height:1000px">
			</div>
		</div>
		<div class="myslider fade">
			<div class="txt">
				<h1>ADIDAS'S SHIRT</h1>
				<p>COME TO BUY OR SELL YOUR PRODUCTS</p>
			</div>
			<div class="style1">
				<img src="../Image/product1.jpg" style="width:100% ;height:1000px">
			</div>
		</div>
		<div class="myslider fade">
			<div class="txt">
				<h1>STAR's GLASS</h1>
				<button style="background-color: black;border-radius:10px;">BUY NOW</button>
			</div>
			<div class="style1">
				<img src="../Image/product5.jpg" style="width:100% ;height:1000px">
			</div>
		</div>

		<a class="prev" onclick="plusSlides(-1)">&#10094;</a>"
		<a class="next" onclick="plusSlides(1)">&#10095;</a>
		<div class="dotsbox" style="text-align: center;">
			<span class="dot" onclick="currentSlide(1)"></span>
			<span class="dot" onclick="currentSlide(2)"></span>
			<span class="dot" onclick="currentSlide(3)"></span>
		</div>

	</div>

